version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./backend/data:/var/lib/postgresql/data
  django:
    build: ./backend
    volumes:
      - ./backend:/app/api
    ports:
      - "8000:8000"
    depends_on:
      - db
    entrypoint:
      - "/app/api/api-entrypoint.sh"
  frontend:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules:
